
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CATEGORIA COLONS NUMERO PVIRG TIPO TRACOcategorias : CATEGORIA COLONS entrada categoriasentrada : TRACO NUMERO COLONS TIPO COLONS NUMERO COLONS NUMERO PVIRG entradacategorias : emptyentrada : emptyempty :'
    
_lr_action_items = {'CATEGORIA':([0,4,5,7,16,17,],[2,-5,2,-4,-5,-2,]),'$end':([0,1,3,4,5,7,8,16,17,],[-5,0,-3,-5,-5,-4,-1,-5,-2,]),'COLONS':([2,9,11,13,],[4,10,12,14,]),'TRACO':([4,16,],[6,6,]),'NUMERO':([6,12,14,],[9,13,15,]),'TIPO':([10,],[11,]),'PVIRG':([15,],[16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'categorias':([0,5,],[1,8,]),'empty':([0,4,5,16,],[3,7,3,7,]),'entrada':([4,16,],[5,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> categorias","S'",1,None,None,None),
  ('categorias -> CATEGORIA COLONS entrada categorias','categorias',4,'p_categorias','listacompras.py',80),
  ('entrada -> TRACO NUMERO COLONS TIPO COLONS NUMERO COLONS NUMERO PVIRG entrada','entrada',10,'p_entrada','listacompras.py',84),
  ('categorias -> empty','categorias',1,'p_categorias_empty','listacompras.py',88),
  ('entrada -> empty','entrada',1,'p_entrada_empty','listacompras.py',92),
  ('empty -> <empty>','empty',0,'p_empty','listacompras.py',97),
]
