
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA LCHAR PASTA RCHARdiretoria : PASTA LCHAR conteudo RCHARconteudo : entrada COMMA conteudoconteudo : entradaentrada : PASTA LCHAR RCHARentrada : PASTA LCHAR conteudo RCHARentrada : PASTA diretoria : emptyempty :'
    
_lr_action_items = {'PASTA':([0,4,8,10,],[2,5,5,5,]),'$end':([0,1,3,9,],[-8,0,-7,-1,]),'LCHAR':([2,5,],[4,8,]),'COMMA':([5,7,11,14,],[-6,10,-4,-5,]),'RCHAR':([5,6,7,8,11,12,13,14,],[-6,9,-3,11,-4,14,-2,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'diretoria':([0,],[1,]),'empty':([0,],[3,]),'conteudo':([4,8,10,],[6,12,13,]),'entrada':([4,8,10,],[7,7,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> diretoria","S'",1,None,None,None),
  ('diretoria -> PASTA LCHAR conteudo RCHAR','diretoria',4,'p_diretoria','filesystem,py',56),
  ('conteudo -> entrada COMMA conteudo','conteudo',3,'p_conteudo_1caso','filesystem,py',62),
  ('conteudo -> entrada','conteudo',1,'p_conteudo_2caso','filesystem,py',66),
  ('entrada -> PASTA LCHAR RCHAR','entrada',3,'p_entrada_1caso','filesystem,py',70),
  ('entrada -> PASTA LCHAR conteudo RCHAR','entrada',4,'p_entrada_2caso','filesystem,py',75),
  ('entrada -> PASTA','entrada',1,'p_entrada_3caso','filesystem,py',81),
  ('diretoria -> empty','diretoria',1,'p_diretoria_empty','filesystem,py',86),
  ('empty -> <empty>','empty',0,'p_empty','filesystem,py',92),
]
